spring:

#<-- Database config --># 
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        hibernate:
            ddl-auto: create-drop
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        database: H2
        show-sql: true
        
#<-- Server configuration -->
server:
    port: 9000
    
#<-- Properties -->
cep:
    url: http://localhost:8080/addresses